language: julia

os:
  - linux
  - osx
  - windows
  - freebsd

arch:
  - amd64
  - arm64

julia:
  - 1.3
  
matrix:
  exclude:
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
    - julia: nightly
      arch: arm64

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

jobs:
  include:
    - stage: Documentation
      julia: 1.3
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs docs/make.jl
      after_success: skip

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
